### ISSUE TITLE
Please allow for different cpu governor policies

### ISSUE THREAD

**Issue by LethalManBoob** [blacksky3/linux-lqx#5]
I do not want my cpu always running at high speeds with performance. ondemand and conservative policys would be appreciated. Thank you.

**Comment by blacksky3** [comment]
Since commit : https://github.com/blacksky3/linux-lqx/tree/25e189b03fac83a365cc622b0bc1e95bec41b5ed we keep the original config of liquorix package

**Comment by LethalManBoob** [comment]
Oh that was strange. i install the base lqx to test and the noted performance govs where there. reinstalled this one and now they are here to. must have hit a very strange glitch
