### ISSUE TITLE
linux-lqx-bmq is currently unable to be downloaded

### ISSUE THREAD

**Issue by LethalManBoob** [blacksky3/linux-lqx#6]
error: failed retrieving file 'linux-lqx-bmq-5.19.4_lqx1-1-x86_64.pkg.tar.zst.sig' from repo.blacksky3.com : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.

**Comment by LethalManBoob** [comment]
fixed but now i get this error
error: linux-lqx-bmq: missing required signature
error: linux-lqx-bmq-headers: missing required signature
error: failed to commit transaction (package missing required signature)

**Comment by blacksky3** [comment]
Package are not signed

Add this to your pacman.conf or ajust it to accept no signed package

[kernel]
SigLevel = Optional TrustAll
Server = https://repo.blacksky3.com/$arch/$repo

**Comment by LethalManBoob** [comment]
Thank you. My mistake
